MAX_PRICE_DROP_PCT_5M = 3
MAX_PRICE_DROP_PCT_15M = 6
MAX_PRICE_DROP_PCT_30M = 8
MAX_PRICE_DROP_PCT_1H = 10
MAX_PRICE_DROP_PCT_2H = 15
MAX_PRICE_DROP_PCT_4H = 20
MAX_PRICE_DROP_PCT_12H = 30

MAX_OI_INCREASE_PCT_5M = 5
MAX_OI_INCREASE_PCT_15M = 10
MAX_OI_INCREASE_PCT_30M = 20
MAX_OI_INCREASE_PCT_1H = 25
MAX_OI_INCREASE_PCT_2H = 40
MAX_OI_INCREASE_PCT_4H = 50
MAX_OI_INCREASE_PCT_12H = 75

MAX_PINBAR_RATIO_ATR = 4
MAX_RSI = 100

max_limits_oi_plot = {
    '5m': (MAX_PRICE_DROP_PCT_5M, MAX_OI_INCREASE_PCT_5M),
    '15m': (MAX_PRICE_DROP_PCT_15M, MAX_OI_INCREASE_PCT_15M),
    '30m': (MAX_PRICE_DROP_PCT_30M, MAX_OI_INCREASE_PCT_30M),
    '1h': (MAX_PRICE_DROP_PCT_1H, MAX_OI_INCREASE_PCT_1H),
    '2h': (MAX_PRICE_DROP_PCT_2H, MAX_OI_INCREASE_PCT_2H),
    '4h': (MAX_PRICE_DROP_PCT_4H, MAX_OI_INCREASE_PCT_4H),
    '12h': (MAX_PRICE_DROP_PCT_12H, MAX_OI_INCREASE_PCT_12H),
}