name: oi_live_scan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Specify your Python version
  - pandas
  - pip
  - pip:
    - plotly
    - discordwebhook
    - requests
    - binance-futures-connector
    - kaleido